version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "5174:5174"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    tty: true
    env_file:
      - .env

  rest_api:
    container_name: rest_api
    build:
      context: ./rest_api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./rest_api:/app
    depends_on:
      - db
    tty: true
    env_file:
      - .env

  db:
    container_name: db
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
      

volumes:
  db-data: