# Python の公式イメージをベースにします
FROM python:3.9.19

USER root
# ワーキングディレクトリを設定します
WORKDIR /app

# 必要なパッケージをインストールします
RUN apt-get update && \
    apt-get install -y ffmpeg

# /tmp_audio/ ディレクトリの所有者を非rootユーザーに変更
# RUN mkdir /tmp_audio/ && chown 1000:1000 /tmp_audio/

# requirements.txt をコピーし、依存関係をインストールします
# USER 1000
COPY requirements.txt ./
RUN python -m pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# プロジェクトのファイルをコピーします
COPY . .

# Django アプリケーションを実行します
CMD ["python", "manage.py", "runserver", "0.0.0.0:8081"]

